coverage:
  status:
    project:
      default:
        target: 85%
        threshold: 2%
    patch:
      default:
        target: 80%

ignore:
  - "api/v1alpha1/zz_generated.deepcopy.go"
  - "cmd/*/main.go"
  - "**/*_test.go"
