version: "2"

run:
  timeout: 5m

formatters:
  enable:
    - gofmt

linters:
  default: none
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - misspell
  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
        - (net/http.ResponseWriter).Write
        - (*go.uber.org/zap.Logger).Sync
        - (*github.com/spf13/cobra.Command).MarkFlagRequired
        - (*text/tabwriter.Writer).Flush
        - (*encoding/json.Encoder).Encode
  exclusions:
    paths:
      - "zz_generated.*"
    rules:
      - linters:
          - errcheck
        path: _test\.go
      - linters:
          - errcheck
        text: ".Close()"
