# ConstraintProfile examples.
# Use ConstraintProfiles to register custom CRDs with Potoo's discovery engine
# or to override adapter settings for known CRD types.

# Register a custom company CRD as a constraint source.
# Potoo will watch this CRD and parse it using the generic adapter.
apiVersion: potoo.io/v1alpha1
kind: ConstraintProfile
metadata:
  name: company-deployment-restrictions
spec:
  gvr:
    group: policy.internal.company.com
    version: v1
    resource: deploymentrestrictions
  adapter: generic
  enabled: true
  severity: Warning
  debounceSeconds: 60
  # Custom field paths tell the generic adapter where to find selectors and effects.
  fieldPaths:
    selectorPath: "spec.target.workloads"
    namespaceSelectorPath: "spec.scope.namespaces"
    effectPath: "spec.action"
    summaryPath: "spec.description"
---
# Override settings for Cilium network policies.
# Raises severity to Critical and reduces debounce for faster notifications.
apiVersion: potoo.io/v1alpha1
kind: ConstraintProfile
metadata:
  name: cilium-network-policies
spec:
  gvr:
    group: cilium.io
    version: v2
    resource: ciliumnetworkpolicies
  adapter: cilium
  enabled: true
  severity: Critical
  debounceSeconds: 30
